import frappe

@frappe.whitelist()
def before_save(doc, method):
    doc.custom_return_delivery_note_item = []
    if any(row.custom_return == 1 for row in doc.items):
        for item in doc.items:
            if item.custom_return == 1:
                doc.append("custom_return_delivery_note_item", {
                    "barcode": item.barcode,
                    "has_item_scanned": item.has_item_scanned,
                    "item_code": item.item_code,
                    "item_name": item.item_name,
                    "customer_item_code": item.customer_item_code,
                    "description": item.description,
                    "brand": item.brand,
                    "item_group": item.item_group,
                    "image": item.image,
                    "qty": item.qty,
                    "stock_uom": item.stock_uom,
                    "uom": item.uom,
                    "conversion_factor": item.conversion_factor,
                    "stock_qty": item.stock_qty,
                    "returned_qty": item.returned_qty,
                    "price_list_rate": item.price_list_rate,
                    "base_price_list_rate": item.base_price_list_rate,
                    "margin_type": item.margin_type,
                    "margin_rate_or_amount": item.margin_rate_or_amount,
                    "rate_with_margin": item.rate_with_margin,
                    "discount_percentage": item.discount_percentage,
                    "discount_amount": item.discount_amount,
                    "base_rate_with_margin": item.base_rate_with_margin,
                    "rate": item.rate,
                    "amount": item.amount,
                    "base_rate": item.base_rate,
                    "base_amount": item.base_amount,
                    "pricing_rules": item.pricing_rules,
                    "stock_uom_rate": item.stock_uom_rate,
                    "is_free_item": item.is_free_item,
                    "grant_commission": item.grant_commission,
                    "net_rate": item.net_rate,
                    "net_amount": item.net_amount,
                    "item_tax_template": item.item_tax_template,
                    "base_net_rate": item.base_net_rate,
                    "base_net_amount": item.base_net_amount,
                    "billed_amt": item.billed_amt,
                    "incoming_rate": item.incoming_rate,
                    "weight_per_unit": item.weight_per_unit,
                    "total_weight": item.total_weight,
                    "weight_uom": item.weight_uom,
                    "warehouse": item.warehouse,
                    "target_warehouse": item.target_warehouse,
                    "quality_inspection": item.quality_inspection,
                    "allow_zero_valuation_rate": item.allow_zero_valuation_rate,
                    "against_sales_order": item.against_sales_order,
                    "so_detail": item.so_detail,
                    "against_sales_invoice": item.against_sales_invoice,
                    "si_detail": item.si_detail,
                    "dn_detail": item.dn_detail,
                    "pick_list_item": item.pick_list_item,
                    "serial_no": item.serial_no,
                    "batch_no": item.batch_no,
                    "actual_qty": item.actual_qty,
                    "actual_batch_qty": item.actual_batch_qty,
                    "company_total_stock": item.company_total_stock,
                    "installed_qty": item.installed_qty,
                    "packed_qty": item.packed_qty,
                    "received_qty": item.received_qty,
                    "expense_account": item.expense_account,
                    "item_tax_rate": item.item_tax_rate,
                    "material_request": item.material_request,
                    "purchase_order": item.purchase_order,
                    "purchase_order_item": item.purchase_order_item,
                    "material_request_item": item.material_request_item,
                    "cost_center": item.cost_center,
                    "page_break": item.page_break,
                    "custom_return": item.custom_return,
                    "custom_reason": item.custom_reason
                })